COMPONENT=UDPSendMonAppC

# Should derive a local link address from (PANID) and TOS_NODE_ID, but
# seems quite ineffective. 
#PFLAGS += -DBLIP_DERIVE_SHORTADDRS

# Suppress creation of a global ipv6.
PFLAGS += -DIN6_NO_GLOBAL

include $(MAKERULES)
